swagger: '2.0'
info:
  description: FiringCalorie RESTful API
  version: '1.0'
  title: FiringCalorie API
host: firingcalorie.ml
basePath: /v1
schemes:
  - https
paths:
  /cusers/session:
    post:
      tags:
        - cuser
      summary: '2C: 顾客登入'
      parameters:
        - in: body
          name: body
          description: user info for login
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: simpleUsername
      responses:
        '200':
          description: successfully login
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully login.
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '404':
          description: restaurant id not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Restaurant not found.
    put:
      tags:
        - cuser
      summary: '2C: 顾客登出'
      responses:
        '200':
          description: successfully logout
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully logout
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
  /busers/avatar:
    get:
      tags:
        - buser
      summary: 2B：商家获取图片
      responses:
        '200':
          description: successfully get the avatar path
          schema:
            type: object
            properties:
              path:
                type: string
                example: static/images/users/4a47a0db6e.png
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
    put:
      tags:
        - buser
      summary: 2B：商家更改图片
      parameters:
        - in: body
          name: body
          description: image URL encoded by png;base64
          required: true
          schema:
            type: object
            properties:
              data:
                type: string
                example: 'data:image/png;base64,.....'
      responses:
        '200':
          description: successfully upload avatar
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully upload
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
  /busers/password:
    put:
      tags:
        - buser
      summary: '2B: 商家改密码'
      parameters:
        - in: body
          name: body
          description: register info
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
                example: naviePassword
      responses:
        '200':
          description: successfully change password
          schema:
            type: object
            properties:
              message:
                type: string
                example: Change password successfully.
        '400':
          description: invalid password
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid password.
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
  /busers/session:
    post:
      tags:
        - buser
      summary: '2B: 商家登录'
      parameters:
        - in: body
          name: body
          description: user info for login
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: simpleUsername
              password:
                type: string
                example: naviePassword
      responses:
        '200':
          description: successfully login
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully login.
        '401':
          description: invalid username or password
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid username or password.
        '404':
          description: restaurant id not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Restaurant not found.
    put:
      tags:
        - buser
      summary: '2B: 商家登出'
      responses:
        '200':
          description: successfully logout
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully logout.
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required
  /menus/:
    post:
      tags:
        - menu
      summary: '2B: 给该餐馆新建菜单'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 只需要菜单名，排序，是否使用
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: 春季菜单
              rank:
                type: integer
                example: 1
              used:
                type: boolean
                example: 1
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Add a new menu successfully
              id:
                type: integer
                example: 1
    get:
      tags:
        - menu
      summary: '2B: 获取所有菜单'
      consumes:
        - application/json
      responses:
        '200':
          description: Successful delete for menu info
          schema:
            type: object
            properties:
              menus:
                type: array
                items:
                  $ref: '#/definitions/Menu'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: Menu not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Menu not found
  /menus/<menuid>:
    put:
      tags:
        - menu
      summary: '2B: 给该餐馆修改菜单'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 不要使用该api修改类别和菜！
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: 春季菜单
              rank:
                type: integer
                example: 1
              used:
                type: boolean
                example: 1
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Modify a new menu successfully
    get:
      tags:
        - menu
      summary: '2B: 获取某一菜单'
      consumes:
        - application/json
      responses:
        '200':
          description: Successful query for menu info
          schema:
            $ref: '#/definitions/Menu'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: Menu not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Menu not found
    delete:
      tags:
        - menu
      summary: '2B: 删除某一菜单'
      consumes:
        - application/json
      responses:
        '200':
          description: Successful delete for menu info
          schema:
            type: object
            properties:
              message:
                type: string
                example: OK
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: Menu not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Menu not found
  /menus/<menuid>/categories/:
    post:
      tags:
        - category
      summary: '2B: 在某一菜单下新增一个类别'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 不需要id和dishes
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '200':
          description: add a new category successfully
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 3910
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority.
  /menus/<menuid>/categories/<catId>:
    delete:
      tags:
        - category
      summary: '2B: 在某一菜单下删除一个类别'
      consumes:
        - application/json
      responses:
        '200':
          description: delete a category successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: OK
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority.
        '444':
          description: error message
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
    put:
      tags:
        - category
      summary: '2B: 在某一菜单下修改一个类别'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: '不需要id和dishes, 只需提交要修改的字段, 请不要在这里修改dish'
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '200':
          description: delete a category successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: OK
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority.
        '444':
          description: error message
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
  /menus/<menuid>/categories/<catId>/dishes/:
    post:
      tags:
        - dish
      summary: '2B: 在某一菜单下新增一个菜'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Dish object to add into database. Id is not needed
          required: true
          schema:
            $ref: '#/definitions/Dish'
      responses:
        '200':
          description: add a new dish successfully
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 3910
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority.
  /menus/<menuid>/categories/<catId>/dishes/<dishId>:
    get:
      tags:
        - dish
      summary: '2B&2C: 获取一个菜'
      consumes:
        - application/json
      responses:
        '200':
          description: Successful query for dish info
          schema:
            $ref: '#/definitions/Dish'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: dish not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dish not found
    put:
      tags:
        - dish
      summary: '2B: 更新一个菜'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Dish object with update information. Id is not needed
          required: true
          schema:
            $ref: '#/definitions/Dish'
      responses:
        '200':
          description: Successful update
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority.
        '404':
          description: dish Not Found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dish not found
    delete:
      tags:
        - dish
      summary: '2B: 删除一个菜'
      consumes:
        - application/json
      responses:
        '200':
          description: successfully delete
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully delete.
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '403':
          description: lack of authority
          schema:
            type: object
            properties:
              message:
                type: string
                example: Lack of authority
        '404':
          description: dish not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dish not found.
  /restrt:
    get:
      tags:
        - restrt
      summary: '2C: 获取餐馆信息'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Restaurant'
        '404':
          description: restaurant not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Restaurant not found
    put:
      tags:
        - restrt
      summary: '2B: 修改餐馆信息'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'Dishes format should be ''<dishId>, <dishId>...'''
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: 点都德
              description:
                type: string
                example: 一个吃饭的地方
              img:
                type: string
                example: example.com/1.jpg
              open:
                type: string
                format: date-time
                example: '2017-11-23 16:10:10'
              close:
                type: string
                format: date-time
                example: '2017-11-23 16:10:10'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Modify restrt info successfully.
  /orders/cuser/:
    post:
      tags:
        - order
      summary: '用户提交订单, total为原总价, due为折后总价'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 提交订单
          required: true
          schema:
            type: object
            properties:
              tableId:
                type: string
                example: 23E
              total:
                type: number
                format: float
                example: 100.8
              due:
                type: number
                format: float
                example: 90.8
              content:
                type: array
                items:
                  type: object
                  properties:
                    dish:
                      type: integer
                      example: 1
                    quantity:
                      type: integer
                      example: 2
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              orderId:
                type: integer
                example: 4396
        '400':
          description: wrong order
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[invalid order form message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
    get:
      tags:
        - order
      summary: '2C: 用户获取全部订单'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              orders:
                type: array
                items:
                  $ref: '#/definitions/Order'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required and you can only get your own order(s).
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found.
  /orders/cuser/oid/<orderid>:
    get:
      tags:
        - order
      summary: '2C: 用户获取单个订单'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found
    
    delete:
      tags:
        - order
      summary: '2C: 用户删除未支付订单'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: delete successfully
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found

    put:
      tags:
        - order
      summary: 用户修改订单信息
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: '可以修改的字段: orderItem中的urge和like.'
          required: true
          schema:
            type: object
            properties:
              orderItemId:
                type: integer
                example: 123
              like:
                type: integer
                example: 1
              urge:
                type: integer
                example: 2
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully modify.
    post:
      tags:
        - order
      summary: '2C: 订单付款'
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: payment id and the corresponding order id
          required: true
          schema:
            type: object
            properties:
              payId:
                type: integer
                example: 2200
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully pay.
        '400':
          description: 'ayid is wrong, no such payment'
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Payid is wrong, no such payment.'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found.
  /orders/buser/oid/<orderId>:
    get:
      tags:
        - order
      summary: '2B: 商家获取一个订单'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required and you can only get your own order.
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found.
    put:
      tags:
        - order
      summary: 商家修改订单
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: '可以修改的字段: orderItem中的finished和time.'
          required: true
          schema:
            type: object
            properties:
              orderItemId:
                type: integer
                example: 123
              time:
                type: string
                format: date-time
                example: '2018-06-21 19:00:00'
              finished:
                type: integer
                example: 1
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully modify.
  /orders/buser/:
    get:
      tags:
        - order
      summary: '2B: 商家获取全部订单'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              orders:
                type: array
                items:
                  $ref: '#/definitions/Order'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: order not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Order not found.
  /promotions/:
    get:
      tags:
        - promotion
      summary: 获取活动列表(customer 获取当前有效的，manager 获取所有的)
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              promotions:
                type: array
                items:
                  $ref: '#/definitions/Promotion'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: promotions not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Promotions not found.
    post:
      tags:
        - promotion
      summary: 新建活动
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: '新建活动,只需要theme, begin, end, isend'
          required: true
          schema:
            $ref: '#/definitions/Promotion'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
  /promotions/<pid>:
    get:
      tags:
        - promotion
      summary: 获取单个活动
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Promotion'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: promotion not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Promotion not found.
    put:
      tags:
        - promotion
      summary: 修改某个活动
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: '修改活动,可以修改theme, begin, end, isend'
          required: true
          schema:
            $ref: '#/definitions/Promotion'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: modify promotion successfully
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: promotion not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Promotion not found.
    delete:
      tags:
        - promotion
      summary: 删除某个活动
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: delete promotion successfully
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: promotion not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: Promotion not found.
  /promotions/<pid>/rules/:
    post:
      tags:
        - rule
      summary: 新建活动规则
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 新建活动规则
          required: true
          schema:
            $ref: '#/definitions/Rule'
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
  /promotions/<pid>/rules/<rid>:
    get:
      tags:
        - rule
      summary: 获取单个活动规则
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Rule'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: rule not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: rule not found.
    put:
      tags:
        - rule
      summary: 修改某个活动规则
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 修改活动规则
          required: true
          schema:
            $ref: '#/definitions/Rule'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Rule'
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: '[error message]'
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: rule not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: rule not found.
    delete:
      tags:
        - rule
      summary: 删除某个活动规则
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                example: delete rule successfully
        '401':
          description: login required
          schema:
            type: object
            properties:
              message:
                type: string
                example: Login required.
        '404':
          description: rule not found
          schema:
            type: object
            properties:
              message:
                type: string
                example: rule not found.

  /analytics/turnover:
    get:
      parameters:
        - in: path
          name: days
          type: integer
          required: true
          description: Only 7 or 30 days are available.
      tags:
        - analytics
      summary: '获取交易额统计'
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              xAxis:
                type: string
                example: ['6月23日', '6月24日', '6月25日', '6月26日', '6月27日', '6月28日', '6月29日']
              data:
                type: object
                example:
                  - name: '主食'
                    data: [320, 332, 301, 334, 390, 330, 320]
                  - name: '肉类'
                    data: [120, 132, 101, 134, 90, 230, 210]
                  - name: '青菜'
                    data: [257, 358, 278, 234, 290, 330, 310]

  /analytics/count/card:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - todayUser: 123
                todayNewUser: 128
                todayTurnover: 43805
                todayDish: 3950

  /analytics/count/orders:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - name: '周一'
                value: 453
              - name: '周二'
                value: 879
              - name: '周三'
                value: 235
              - name: '周四'
                value: 159
              - name: '周五'
                value: 130
              - name: '周六'
                value: 543
              - name: '周日'
                value: 130

  /analytics/count/payWay:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - name: '微信'
                value: 453
              - name: '支付宝'
                value: 879
              - name: '支付宝'
                value: 235
              - name: '比特币'
                value: 159

  /analytics/count/finishTime:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              order:
                - avg: 49
                  max: 60
              dish:
                - avg: 18
                  max: 30

  /analytics/rank/likes:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - name: '牛板筋'
                value: 250
              - name: '香菇炖鸡'
                value: 141
              - name: '白切鸡'
                value: 138
              - name: '油焖小龙虾'
                value: 74

  /analytics/rank/sales:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - name: '麻辣香锅'
                value: 3421
              - name: '牛板筋'
                value: 2444
              - name: '香菇炖鸡'
                value: 1111
              - name: '油焖小龙虾'
                value: 910

  /analytics/summary:
    get:
      tags:
        - analytics
      summary: ''
      consumes:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            example:
              - date: '2018-06-17'
                dayOrder: 123
                dayDish: 321
                dayAvgOrderFinishTime: 31
                dayAvgDishFinishTime: 15
                dayDue: 12
                dayTotal: 1500
              - date: '2018-06-18'
                dayOrder: 123
                dayDish: 321
                dayAvgOrderFinishTime: 31
                dayAvgDishFinishTime: 15
                dayDue: 12511
                total: 1500
              - date: '2018-06-19'
                dayOrder: 123
                dayDish: 321
                dayAvgOrderFinishTime: 31
                dayAvgDishFinishTime: 15
                dayDue: 1240
                dayTotal: 1500


definitions:
  Turnover:
    type: object
    properties:
      name:
        type: string
        example: meat
      data:
        type: integer
        example:
          - 320
          - 330
          - 332
          - 294
          - 345
          - 212
          - 377

  Dish:
    type: object
    properties:
      id:
        type: integer
        example: 3910
      name:
        type: string
        example: 毛血旺
      rank:
        type: integer
        example: 1
      img:
        type: string
        example: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAA'
      price:
        type: number
        format: float
        example: 28.5
      stock:
        type: integer
        example: 99
      avaliable:
        type: integer
        example: 1
      likes:
        type: integer
        example: 4
      description:
        type: string
        example: Hello 毛血旺
    required:
      - name
      - price
  Menu:
    type: object
    properties:
      id:
        type: integer
        example: 10
      name:
        type: string
        example: springMenu
      used:
        type: integer
        example: 1
      content:
        type: array
        items:
          $ref: '#/definitions/Category'
    required:
      - name
  Order:
    type: object
    properties:
      id:
        type: integer
        example: 4396
      userId:
        type: integer
        example: 10
      tableId:
        type: string
        example: 23E
      total:
        type: number
        format: float
        example: 108.3
      due:
        type: number
        format: float
        example: 92.3
      isPay:
        type: integer
        example: 1
      payWay:
        type: string
        example: alipay
      payDate:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      payId:
        type: integer
        example: 123
      dishes:
        type: array
        items:
          $ref: '#/definitions/Dish'
      orderItems:
        type: array
        items:
          $ref: '#/definitions/OrderItem'
      finished:
        type: integer
        example: 1
  OrderItem:
    type: object
    properties:
      id:
        type: integer
        example: 1
      orderId:
        type: integer
        example: 2
      dishId:
        type: integer
        example: 3
      quantity:
        type: integer
        example: 2
      finished:
        type: integer
        example: 1
      time:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      urge:
        type: integer
        example: 1
      like:
        type: integer
        example: 0
  Promotion:
    type: object
    properties:
      id:
        type: integer
        example: 1
      theme:
        type: string
        example: 端午节活动
      begin:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      end:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      isend:
        type: integer
        example: 1
      rules:
        type: array
        items:
          $ref: '#/definitions/Rule'
  Rule:
    type: object
    properties:
      id:
        type: integer
        example: 1
      mode:
        type: integer
        example: '1(满减), 2(满折)'
      requirement:
        type: number
        format: float
        example: 100
      discount:
        type: number
        format: float
        example: 10
  Category:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: 荤菜
      rank:
        type: integer
        example: 1
      dishes:
        type: array
        items:
          $ref: '#/definitions/Dish'
  Restaurant:
    type: object
    properties:
      name:
        type: string
        example: 点都德
      description:
        type: string
        example: ddd
      img:
        type: string
        example: example.com/1.jpg
      open:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      close:
        type: string
        format: date-time
        example: '2017-11-23 16:10:10'
      menus:
        type: array
        items:
          $ref: '#/definitions/Menu'
      carousels:
        type: array
        items:
          $ref: '#/definitions/Carousel'
  Carousel:
    type: object
    properties:
      id:
        type: number
        example: 1
      info:
        type: string
        example: some info here
      img:
        type: string
        example: example.com/1.jpg
